name: Build and publish dockerfile
 
on:
  push:
    branches:
      - master
 
env:
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD:  ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD:  ${{ secrets.MYSQL_ROOT_PASSWORD }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  IMAGE: future-tracking-mysql-migrations

jobs:
  build-docker-image: 
    runs-on: ubuntu-latest  
    name: Build and publish Docker container
    steps:
    - uses: actions/checkout@v1

    - name: Build Docker container
      run: docker build -f Dockerfile -t future-tracking-mysql-migrations . --tag gcr.io/$GKE_PROJECT/$IMAGE

    - name: install python-openssl
      run: sudo apt-get install -y python-openssl -o=Dpkg::Use-Pty=0

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: gcloud auth configure-docker

    - name: Publish
      run: docker push gcr.io/$GKE_PROJECT/$IMAGE